SNS_ROLE_ARN: ENV['SNS_ROLE_ARN']
ENDPOINT: ENV['ENDPOINT']
AWS_ACCESS_KEY_ID: ENV['AWS_ACCESS_KEY_ID']
AWS_SECRET_ACCESS_KEY: ENV['AWS_SECRET_ACCESS_KEY']
AWS_REGION: ENV['AWS_REGION']
DATABASE_URL: ENV['DATABASE_URL']
